### ISSUE TITLE
internations/http-mock dev-master is not existed anymore. 

### ISSUE THREAD

**Issue by inthra-onsap** [mcustiel/codeception-http-mock#1]
I found the issue that I can not run "composer require mcustiel/codeception-http-mock".
 Problem 1
    - Installation request for mcustiel/codeception-http-mock ^0.5.0 -> satisfiable by mcustiel/codeception-http-mock[v0.5].
    - mcustiel/codeception-http-mock v0.5 requires internations/http-mock dev-master -> no matching package found.

Could you change the internations/http-mock version from "dev-master" to version number?

**Comment by mcustiel** [comment]
Hi. I was using dev-master because it was really improved from the latest released version. Now I see there is a release from 21 days ago. so I will change it and run some tests.
In the meantime, you can use "minimum-stability": "dev" in your composer.json file to allow it to use the dev-master version.

**Comment by mcustiel** [comment]
Fixed in version 0.5.1
